### ISSUE TITLE
Mobile Menu Bug

### ISSUE THREAD

**Issue by YannHun** [Bbc-Team-H/Bewik-Website#1]
**Describe the bug**
When you open the menu on mobile is teleports in the right corner and jumps back to the correct position.

**To Reproduce**
1. Go to 'Bewik Website'
2. Click on 'Menu Icon'

**Expected behavior**
When you open the menu the menu immediately is in the correct position

**Device**
 - Device: [Iphone XR]
 - Browser [Safari & Chrome]

**Comment by J4yTr1n1ty** [comment]
+1 for me
Device: iPhone X
Browser: Safari

**Comment by Dalurei** [comment]
It works on my device
Device: Samsung Galaxy A51
Browser: Samsung Internet

**Comment by J4yTr1n1ty** [comment]
**Fixed** though not doing a Transition at all. @YannHun
